[workspace]
resolver = "2"
members = ["audiowire", "audiowire_sys", "audiowire_derive", "audiowire_serde"]

[workspace.dependencies]
anyhow = "1.0.102"
audiowire_derive = { path = "./audiowire_derive" }
audiowire_serde = { path = "./audiowire_serde" }
audiowire_sys = { path = "./audiowire_sys" }
bindgen = "0.72.1"
chrono = "0.4.44"
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = "2.0.117"
