[package]
name = "audiowire"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
audiowire_derive = { workspace = true }
audiowire_sys = { workspace = true }
audiowire_serde = { workspace = true }
bytes = { workspace = true }
chrono = "0.4"
clap = "4.5"
env_logger = { version = "0.11", features = ["kv"] }
log = { workspace = true, features = ["kv", "kv_std", "serde"] }
opus = "0.3"
tokio = { workspace = true, features = ["rt-multi-thread", "net", "io-util", "time", "sync", "signal", "macros"] }

[[bin]]
name = "audiowire-udp-server"
path = "./src/bin/udp_server.rs"

[[bin]]
name = "audiowire-udp-client"
path = "./src/bin/udp_client.rs"
